version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.7.3-stretch
      
    working_directory: ~/flask-sklearn
    
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: Install dependencies
          command: |
            #which python3
            make setup
            source ~/.devops/bin/activate
            make install
            
      - save_cache:
          paths:
            - ./ML-microservice-api
          key: v1-dependencies-{{ checksum "requirements.txt" }}
            
      - run:
          name: run lint
          command: |
            source ~/.devops/bin/activate
            make lint